import * as recast from "recast";

import { Generator, GeneratorResult } from "./generator";

import { ParseNode } from "../grammar/helpers";
import { time } from "../perf-util";

export type VisitResult<T = unknown> = {
  node?: RecastAstNode;
  customState?: T;
  stop?: boolean;
};

type RecastVisitor = (node: ParseNode, astStack: RecastAstNode[]) => VisitResult | null;
type InternalVisitResult = { result: VisitResult; ast: RecastAstNode[] };

export type RecastAstNode = recast.types.namedTypes.Node;

export abstract class RecastGenerator extends Generator {
  protected builder = recast.types.builders;
  protected program = this.builder.program([]);
  protected abstract readonly type: string;

  constructor(root: ParseNode) {
    super(root);
  }

  private attemptVisit(node: ParseNode, ast: RecastAstNode[]): InternalVisitResult {
    const nodeName = node.name || node.tokenType?.name;
    let result: VisitResult = null;

    if (nodeName) {
      const func: RecastVisitor = this[nodeName];

      if (func) {
        result = func.apply(this, [node, ...ast]);

        if (result?.node) {
          ast = [result.node, ...ast];
        }
      } else {
        // console.log(`No handler for ${nodeName}`);
      }
    }

    return {
      result,
      ast
    };
  }

  public async process(): Promise<GeneratorResult> {
    this.program.comments = [this.builder.commentLine(` @autogenerated Generated by ${this.constructor.name}`)];
    this.program.body = [];

    // Visit the root node explicitly
    // TODO: Not very clean to ignore children, but...
    const walkTimeHandle = time();

    type TreeStackNode = { node: ParseNode; ast: RecastAstNode[] };
    let ast: RecastAstNode[] = [this.program];

    const rootResult = this.attemptVisit(this.root, ast);

    if (rootResult?.result?.node) {
      ast = [rootResult.result.node, ...ast];
    }

    if (!rootResult?.result?.stop) {
      const mapRootRule = (parseNode: ParseNode[]): TreeStackNode[] => {
        if (!parseNode) {
          return null;
        }

        return parseNode.map(i => ({ node: i, ast }));
      };

      // Ensure order of top level items, as the root rule is ordered by node name
      const treeStack: TreeStackNode[] = [
        ...mapRootRule(this.root.children.CommentsRule),
        ...mapRootRule(this.root.children.HeaderRule),
        ...mapRootRule(this.root.children.DefinitionRule),
        ...mapRootRule(this.root.children.PostCommentsRule)
      ].filter(Boolean);

      // Depth first walk of tree
      while (treeStack.length > 0) {
        // eslint-disable-next-line prefer-const
        let { node, ast } = treeStack.pop();

        const visit = this.attemptVisit(node, ast);
        ast = visit.ast;

        if (!visit.result || !visit.result.stop) {
          const childKeys = node.children && Object.keys(node.children);
          const hasChildren = childKeys?.length;

          if (hasChildren) {
            // CstNode
            for (const key of childKeys) {
              const childNode = node.children[key];

              treeStack.push(...childNode.map(i => ({ node: i, ast: [...ast] })));
            }
          }
        }
      }
    }

    const walkTime = walkTimeHandle();
    const printTimeHandle = time();
    const output = recast.prettyPrint(this.program);
    const printTime = printTimeHandle();

    return {
      errors: [],
      warnings: [],
      content: [
        {
          type: this.type,
          content: output.code
        },
        {
          type: "map",
          content: output.map
        }
      ],
      timing: {
        print: printTime,
        walk: walkTime
      }
    };
  }

  protected id(name: string): recast.types.namedTypes.Identifier {
    return this.builder.identifier(name);
  }

  protected literal(value: string | number | boolean | RegExp): recast.types.namedTypes.Literal {
    return this.builder.literal(value);
  }
}
